# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jo Space
email: renreine4x1@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
- Hey there, I'm Jolene!
- I’m a software developer who loves building things that make life easier, smarter, or just a little more fun. 

- My toolbox includes JavaScript - React, Angular, React Native, Node.js, TypeScript, C#, Java and Python — plus a sprinkle of design thinking and a whole lot of debugging patience. 
- I’m equally comfortable styling clean UI as I am optimizing backend logic and API calls.

- I’ve worked solo and in teams, in startups and student labs, and I’m always on the lookout for projects where tech meets purpose.

- When I’m not coding, you’ll probably find me playing badminton, brainstorming side projects over coffee, or learning something random on the internet (like how to make a better stir-fry or train a drone to dance).
  
baseurl: '/jospace' # the subpath of your site, e.g. /blog
url: 'https://jolenele.github.io' # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: renreine
instagram_username: ren.reine
github_username: ...
# This site is just a personal blog belonging to someone unknown. Every piece of her mind will be reflected in these writings.

#   Like Virginia Woolf once said - “Every secret of a writer’s soul, every experience of his life, every quality of his mind, is written large in his works.”. 

#   So here you go, welcome to my space!
# Build settings
github: [metadata]
markdown: kramdown
theme: minima
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-github-metadata

gem "github-pages", group: :jekyll_plugins
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# theme: jekyll-theme-architect
